# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('is_student', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Profile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Profile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Profile'),
        ),
        migrations.AlterField(
            model_name='workex',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Profile'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
